apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE_NAME
spec:
  selector:
    matchLabels:
      app: APP_LABEL_VALUE
  replicas: REPLICA_COUNT 
  template:
    metadata:
      labels:
        app: APP_LABEL_VALUE
    spec:
      containers:
      - name: CONTAINER_NAME
        image: CONTAINER_IMAGE
        ports:
        - containerPort: CONTAINER_PORT
